//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DgiiToken
    {
        public int Id { get; set; }
        public string token { get; set; }
        public System.DateTime expira { get; set; }
        public System.DateTime expedido { get; set; }
    }
}
