//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfDetallesItemsItemTablaCodigosItemCodigosItem
    {
        public int Id { get; set; }
        public string TipoCodigo { get; set; }
        public string CodigoItem { get; set; }
        public Nullable<int> ECFDetallesItemsItemId { get; set; }
        public Nullable<int> ECFDetallesItemsItemTablaCodigosItemId { get; set; }
    
        public virtual ECFDetallesItemsItem ECFDetallesItemsItem { get; set; }
        public virtual ECFDetallesItemsItemTablaCodigosItem ECFDetallesItemsItemTablaCodigosItem { get; set; }
    }
}
