//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECFDetallesItemsItemOtraMonedaDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ECFDetallesItemsItemOtraMonedaDetalle()
        {
            this.ECFDetallesItemsItems = new HashSet<ECFDetallesItemsItem>();
        }
    
        public int Id { get; set; }
        public decimal PrecioOtraMonedaValue { get; set; }
        public bool PrecioOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> PrecioOtraMoneda { get; set; }
        public decimal DescuentoOtraMonedaValue { get; set; }
        public bool DescuentoOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> DescuentoOtraMoneda { get; set; }
        public decimal RecargoOtraMonedaValue { get; set; }
        public bool RecargoOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> RecargoOtraMoneda { get; set; }
        public decimal MontoItemOtraMonedaValue { get; set; }
        public bool MontoItemOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoItemOtraMoneda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECFDetallesItemsItem> ECFDetallesItemsItems { get; set; }
    }
}
