//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfDetallesItemsItemTablaSubDescuentoSubDescuento
    {
        public int Id { get; set; }
        public int TipoSubDescuento { get; set; }
        public decimal SubDescuentoPorcentajeValue { get; set; }
        public bool SubDescuentoPorcentajeValueSpecified { get; set; }
        public Nullable<decimal> SubDescuentoPorcentaje { get; set; }
        public decimal MontoSubDescuentoValue { get; set; }
        public bool MontoSubDescuentoValueSpecified { get; set; }
        public Nullable<decimal> MontoSubDescuento { get; set; }
        public Nullable<int> ECFDetallesItemsItemId { get; set; }
        public Nullable<int> ECFDetallesItemsItemTablaSubDescuentoId { get; set; }
    
        public virtual ECFDetallesItemsItem ECFDetallesItemsItem { get; set; }
        public virtual EcfDetallesItemsItemTablaSubDescuento EcfDetallesItemsItemTablaSubDescuento { get; set; }
    }
}
