//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECFDescuentosORecargosDescuentosORecargo
    {
        public int Id { get; set; }
        public short NumeroLinea { get; set; }
        public int TipoAjuste { get; set; }
        public int IndicadorNorma1007Value { get; set; }
        public bool IndicadorNorma1007ValueSpecified { get; set; }
        public Nullable<int> IndicadorNorma1007 { get; set; }
        public string DescripcionDescuentooRecargo { get; set; }
        public int TipoValorValue { get; set; }
        public bool TipoValorValueSpecified { get; set; }
        public Nullable<int> TipoValor { get; set; }
        public decimal ValorDescuentooRecargoValue { get; set; }
        public bool ValorDescuentooRecargoValueSpecified { get; set; }
        public Nullable<decimal> ValorDescuentooRecargo { get; set; }
        public decimal MontoDescuentooRecargoValue { get; set; }
        public bool MontoDescuentooRecargoValueSpecified { get; set; }
        public Nullable<decimal> MontoDescuentooRecargo { get; set; }
        public decimal MontoDescuentooRecargoOtraMonedaValue { get; set; }
        public bool MontoDescuentooRecargoOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoDescuentooRecargoOtraMoneda { get; set; }
        public int IndicadorFacturacionDescuentooRecargoValue { get; set; }
        public bool IndicadorFacturacionDescuentooRecargoValueSpecified { get; set; }
        public Nullable<int> IndicadorFacturacionDescuentooRecargo { get; set; }
        public Nullable<int> ECFDescuentosORecargosId { get; set; }
    
        public virtual ECFDescuentosORecargo ECFDescuentosORecargo { get; set; }
    }
}
