//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfDetallesItemsItemTablaImpuestoAdicionalImpuestoAdicional
    {
        public int Id { get; set; }
        public int TipoImpuesto { get; set; }
        public Nullable<int> ECFDetallesItemsItemId { get; set; }
        public Nullable<int> ECFDetallesItemsItemTablaImpuestoAdicionalId { get; set; }
    
        public virtual ECFDetallesItemsItem ECFDetallesItemsItem { get; set; }
        public virtual ECFDetallesItemsItemTablaImpuestoAdicional ECFDetallesItemsItemTablaImpuestoAdicional { get; set; }
    }
}
