//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfDetallesItemsItemTablaSubRecargoSubRecargo
    {
        public int Id { get; set; }
        public int TipoSubRecargo { get; set; }
        public decimal SubRecargoPorcentajeValue { get; set; }
        public bool SubRecargoPorcentajeValueSpecified { get; set; }
        public Nullable<decimal> SubRecargoPorcentaje { get; set; }
        public decimal MontoSubRecargoValue { get; set; }
        public bool MontoSubRecargoValueSpecified { get; set; }
        public Nullable<decimal> MontoSubRecargo { get; set; }
        public Nullable<int> ECFDetallesItemsItemId { get; set; }
        public Nullable<int> ECFDetallesItemsItemTablaSubRecargoId { get; set; }
    
        public virtual ECFDetallesItemsItem ECFDetallesItemsItem { get; set; }
        public virtual EcfDetallesItemsItemTablaSubRecargo EcfDetallesItemsItemTablaSubRecargo { get; set; }
    }
}
