//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfDetallesItemsItemTablaSubcantidadSubcantidadItem
    {
        public int Id { get; set; }
        public decimal SubcantidadValue { get; set; }
        public bool SubcantidadValueSpecified { get; set; }
        public Nullable<decimal> Subcantidad { get; set; }
        public int CodigoSubcantidadValue { get; set; }
        public bool CodigoSubcantidadValueSpecified { get; set; }
        public Nullable<int> CodigoSubcantidad { get; set; }
        public Nullable<int> ECFDetallesItemsItemId { get; set; }
        public Nullable<int> ECFDetallesItemsItemTablaSubcantidadId { get; set; }
    
        public virtual ECFDetallesItemsItem ECFDetallesItemsItem { get; set; }
        public virtual EcfDetallesItemsItemTablaSubcantidad EcfDetallesItemsItemTablaSubcantidad { get; set; }
    }
}
