//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfDetallesItemsItemTablaSubRecargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EcfDetallesItemsItemTablaSubRecargo()
        {
            this.EcfDetallesItemsItemTablaSubRecargoSubRecargos = new HashSet<EcfDetallesItemsItemTablaSubRecargoSubRecargo>();
        }
    
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EcfDetallesItemsItemTablaSubRecargoSubRecargo> EcfDetallesItemsItemTablaSubRecargoSubRecargos { get; set; }
    }
}
