//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfEncabezadoComprador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EcfEncabezadoComprador()
        {
            this.EcfEncabezadoes = new HashSet<EcfEncabezado>();
        }
    
        public int Id { get; set; }
        public string RNCComprador { get; set; }
        public string RazonSocialComprador { get; set; }
        public string ContactoComprador { get; set; }
        public string CorreoComprador { get; set; }
        public string DireccionComprador { get; set; }
        public int MunicipioCompradorValue { get; set; }
        public bool MunicipioCompradorValueSpecified { get; set; }
        public Nullable<int> MunicipioComprador { get; set; }
        public int ProvinciaCompradorValue { get; set; }
        public bool ProvinciaCompradorValueSpecified { get; set; }
        public Nullable<int> ProvinciaComprador { get; set; }
        public string FechaEntrega { get; set; }
        public string ContactoEntrega { get; set; }
        public string DireccionEntrega { get; set; }
        public string TelefonoAdicional { get; set; }
        public string FechaOrdenCompra { get; set; }
        public string NumeroOrdenCompra { get; set; }
        public string CodigoInternoComprador { get; set; }
        public string ResponsablePago { get; set; }
        public string InformacionAdicionalComprador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EcfEncabezado> EcfEncabezadoes { get; set; }
    }
}
