//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfEncabezadoTransporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EcfEncabezadoTransporte()
        {
            this.EcfEncabezadoes = new HashSet<EcfEncabezado>();
        }
    
        public int Id { get; set; }
        public string Conductor { get; set; }
        public Nullable<decimal> DocumentoTransporteValue { get; set; }
        public Nullable<bool> DocumentoTransporteValueSpecified { get; set; }
        public Nullable<decimal> DocumentoTransporte { get; set; }
        public string Ficha { get; set; }
        public string Placa { get; set; }
        public string RutaTransporte { get; set; }
        public string ZonaTransporte { get; set; }
        public string NumeroAlbaran { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EcfEncabezado> EcfEncabezadoes { get; set; }
    }
}
