//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECFSubtotalesSubtotal
    {
        public int Id { get; set; }
        public short NumeroSubTotalValue { get; set; }
        public bool NumeroSubTotalValueSpecified { get; set; }
        public Nullable<short> NumeroSubTotal { get; set; }
        public string DescripcionSubtotal { get; set; }
        public short OrdenValue { get; set; }
        public bool OrdenValueSpecified { get; set; }
        public Nullable<short> Orden { get; set; }
        public decimal SubTotalMontoGravadoTotalValue { get; set; }
        public bool SubTotalMontoGravadoTotalValueSpecified { get; set; }
        public Nullable<decimal> SubTotalMontoGravadoTotal { get; set; }
        public decimal SubTotalMontoGravadoI1Value { get; set; }
        public bool SubTotalMontoGravadoI1ValueSpecified { get; set; }
        public Nullable<decimal> SubTotalMontoGravadoI1 { get; set; }
        public decimal SubTotalMontoGravadoI2Value { get; set; }
        public bool SubTotalMontoGravadoI2ValueSpecified { get; set; }
        public Nullable<decimal> SubTotalMontoGravadoI2 { get; set; }
        public decimal SubTotalMontoGravadoI3Value { get; set; }
        public bool SubTotalMontoGravadoI3ValueSpecified { get; set; }
        public Nullable<decimal> SubTotalMontoGravadoI3 { get; set; }
        public decimal SubTotaITBISValue { get; set; }
        public bool SubTotaITBISValueSpecified { get; set; }
        public Nullable<decimal> SubTotaITBIS { get; set; }
        public decimal SubTotaITBIS1Value { get; set; }
        public bool SubTotaITBIS1ValueSpecified { get; set; }
        public Nullable<decimal> SubTotaITBIS1 { get; set; }
        public decimal SubTotaITBIS2Value { get; set; }
        public bool SubTotaITBIS2ValueSpecified { get; set; }
        public Nullable<decimal> SubTotaITBIS2 { get; set; }
        public decimal SubTotaITBIS3Value { get; set; }
        public bool SubTotaITBIS3ValueSpecified { get; set; }
        public Nullable<decimal> SubTotaITBIS3 { get; set; }
        public decimal SubTotalImpuestoAdicionalValue { get; set; }
        public bool SubTotalImpuestoAdicionalValueSpecified { get; set; }
        public Nullable<decimal> SubTotalImpuestoAdicional { get; set; }
        public decimal SubTotalExentoValue { get; set; }
        public bool SubTotalExentoValueSpecified { get; set; }
        public Nullable<decimal> SubTotalExento { get; set; }
        public decimal MontoSubTotalValue { get; set; }
        public bool MontoSubTotalValueSpecified { get; set; }
        public Nullable<decimal> MontoSubTotal { get; set; }
        public short LineasValue { get; set; }
        public bool LineasValueSpecified { get; set; }
        public Nullable<short> Lineas { get; set; }
        public Nullable<int> ECFSubtotalesId { get; set; }
    
        public virtual EfEcfSubtotalesEnumerable EfEcfSubtotalesEnumerable { get; set; }
    }
}
