//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emisore
    {
        public int Id { get; set; }
        public string RNCEmisor { get; set; }
        public string RazonSocialEmisor { get; set; }
        public string DireccionEmisor { get; set; }
        public string FechaEmision { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> CompradorId { get; set; }
        public Nullable<int> TotalesId { get; set; }
    
        public virtual Compradore Compradore { get; set; }
        public virtual Item Item { get; set; }
        public virtual Totale Totale { get; set; }
    }
}
