//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncabezadoOtraMoneda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncabezadoOtraMoneda()
        {
            this.EcfEncabezadoes = new HashSet<EcfEncabezado>();
            this.EcfEncabezadoOtraMonedaImpuestosAdicionalesOtraMonedaImpuestoAdicionalOtraMonedas = new HashSet<EcfEncabezadoOtraMonedaImpuestosAdicionalesOtraMonedaImpuestoAdicionalOtraMoneda>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TipoMonedaValue { get; set; }
        public Nullable<bool> TipoMonedaValueSpecified { get; set; }
        public Nullable<int> TipoMoneda { get; set; }
        public Nullable<decimal> TipoCambioValue { get; set; }
        public Nullable<bool> TipoCambioValueSpecified { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public Nullable<decimal> MontoGravadoTotalOtraMonedaValue { get; set; }
        public Nullable<bool> MontoGravadoTotalOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoGravadoTotalOtraMoneda { get; set; }
        public Nullable<decimal> MontoGravado1OtraMonedaValue { get; set; }
        public Nullable<bool> MontoGravado1OtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoGravado1OtraMoneda { get; set; }
        public Nullable<decimal> MontoGravado2OtraMonedaValue { get; set; }
        public Nullable<bool> MontoGravado2OtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoGravado2OtraMoneda { get; set; }
        public Nullable<decimal> MontoGravado3OtraMonedaValue { get; set; }
        public Nullable<bool> MontoGravado3OtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoGravado3OtraMoneda { get; set; }
        public Nullable<decimal> MontoExentoOtraMonedaValue { get; set; }
        public Nullable<bool> MontoExentoOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoExentoOtraMoneda { get; set; }
        public Nullable<decimal> TotalITBISOtraMonedaValue { get; set; }
        public Nullable<bool> TotalITBISOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> TotalITBISOtraMoneda { get; set; }
        public Nullable<decimal> TotalITBIS1OtraMonedaValue { get; set; }
        public Nullable<bool> TotalITBIS1OtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> TotalITBIS1OtraMoneda { get; set; }
        public Nullable<decimal> TotalITBIS2OtraMonedaValue { get; set; }
        public Nullable<bool> TotalITBIS2OtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> TotalITBIS2OtraMoneda { get; set; }
        public Nullable<decimal> TotalITBIS3OtraMonedaValue { get; set; }
        public Nullable<bool> TotalITBIS3OtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> TotalITBIS3OtraMoneda { get; set; }
        public Nullable<decimal> MontoImpuestoAdicionalOtraMonedaValue { get; set; }
        public Nullable<bool> MontoImpuestoAdicionalOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoImpuestoAdicionalOtraMoneda { get; set; }
        public Nullable<decimal> MontoTotalOtraMonedaValue { get; set; }
        public Nullable<bool> MontoTotalOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoTotalOtraMoneda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EcfEncabezado> EcfEncabezadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EcfEncabezadoOtraMonedaImpuestosAdicionalesOtraMonedaImpuestoAdicionalOtraMoneda> EcfEncabezadoOtraMonedaImpuestosAdicionalesOtraMonedaImpuestoAdicionalOtraMonedas { get; set; }
    }
}
