//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoEnvio
    {
        public int Id { get; set; }
        public string trackId { get; set; }
        public string codigo { get; set; }
        public string estado { get; set; }
        public string rnc { get; set; }
        public string fechaRecepcion { get; set; }
        public int IdMensajeEnvios { get; set; }
        public List<Mensaje> mensajes { get; set; }
    }
}
