//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExInformacionReferencia
    {
        public int Id { get; set; }
        public string NCFModificado { get; set; }
        public string RNCOtroContribuyente { get; set; }
        public string FechaNCFModificado { get; set; }
        public int CodigoModificacionValue { get; set; }
        public bool CodigoModificacionValueSpecified { get; set; }
        public Nullable<int> CodigoModificacion { get; set; }
    }
}
