//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Emisores = new HashSet<Emisore>();
        }
    
        public int Id { get; set; }
        public int NumeroLinea { get; set; }
        public int IndicadorFacturacion { get; set; }
        public string NombreItem { get; set; }
        public int IndicadorBienoServicio { get; set; }
        public double CantidadItem { get; set; }
        public double PrecioUnitarioItem { get; set; }
        public double DescuentoMonto { get; set; }
        public double SubDescuento { get; set; }
        public double MontoOtraMoneda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emisore> Emisores { get; set; }
    }
}
