//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecepcionResult
    {
        public int Id { get; set; }
        public string trackId { get; set; }
        public string error { get; set; }
        public string mensaje { get; set; }
        public Nullable<int> IdDoc { get; set; }
        public string QR { get; set; }
    
        public virtual EcfEncabezadoIdDoc EcfEncabezadoIdDoc { get; set; }
    }
}
