//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Totale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Totale()
        {
            this.Emisores = new HashSet<Emisore>();
        }
    
        public int Id { get; set; }
        public double MontoGravadoTotal { get; set; }
        public double MontoGravadoI1 { get; set; }
        public double MontoGravadoI2 { get; set; }
        public double ITBIS1 { get; set; }
        public double TotalITBIS { get; set; }
        public double TotalITBIS1 { get; set; }
        public double TotalITBIS2 { get; set; }
        public double MontoTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emisore> Emisores { get; set; }
    }
}
