//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF.Recepcion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AprobacionComercial
    {
        public int Id { get; set; }
        public Nullable<int> IdEmisor { get; set; }
        public Nullable<int> IdDoc { get; set; }
        public Nullable<int> IdTotal { get; set; }
        public Nullable<int> IdRecepcionResult { get; set; }
        public Nullable<int> IdEstadoEnvios { get; set; }
    
        public virtual EcfEncabezadoEmisor EcfEncabezadoEmisor { get; set; }
        public virtual EcfEncabezadoIdDoc EcfEncabezadoIdDoc { get; set; }
        public virtual EcfEncabezadoTotale EcfEncabezadoTotale { get; set; }
        public virtual EstadoEnvio EstadoEnvio { get; set; }
        public virtual RecepcionResult RecepcionResult { get; set; }
    }
}
