//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF.Recepcion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECFDescuentosORecargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ECFDescuentosORecargo()
        {
            this.ECFDescuentosORecargosDescuentosORecargoes = new HashSet<ECFDescuentosORecargosDescuentosORecargo>();
        }
    
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECFDescuentosORecargosDescuentosORecargo> ECFDescuentosORecargosDescuentosORecargoes { get; set; }
    }
}
