//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF.Recepcion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECFDetallesItemsItemRetencion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ECFDetallesItemsItemRetencion()
        {
            this.ECFDetallesItemsItems = new HashSet<ECFDetallesItemsItem>();
        }
    
        public int Id { get; set; }
        public int IndicadorAgenteRetencionoPercepcionValue { get; set; }
        public bool IndicadorAgenteRetencionoPercepcionValueSpecified { get; set; }
        public int IndicadorAgenteRetencionoPercepcion { get; set; }
        public decimal MontoITBISRetenidoValue { get; set; }
        public bool MontoITBISRetenidoValueSpecified { get; set; }
        public decimal MontoITBISRetenido { get; set; }
        public decimal MontoISRRetenidoValue { get; set; }
        public bool MontoISRRetenidoValueSpecified { get; set; }
        public decimal MontoISRRetenido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECFDetallesItemsItem> ECFDetallesItemsItems { get; set; }
    }
}
