//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF.Recepcion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfEncabezadoInformacionale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EcfEncabezadoInformacionale()
        {
            this.EcfEncabezadoes = new HashSet<EcfEncabezado>();
        }
    
        public int Id { get; set; }
        public string FechaEmbarque { get; set; }
        public string NumeroEmbarque { get; set; }
        public string NumeroContenedor { get; set; }
        public Nullable<decimal> NumeroReferenciaValue { get; set; }
        public Nullable<bool> NumeroReferenciaValueSpecified { get; set; }
        public Nullable<decimal> NumeroReferencia { get; set; }
        public Nullable<decimal> PesoBrutoValue { get; set; }
        public Nullable<bool> PesoBrutoValueSpecified { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public Nullable<decimal> PesoNetoValue { get; set; }
        public Nullable<bool> PesoNetoValueSpecified { get; set; }
        public Nullable<decimal> PesoNeto { get; set; }
        public Nullable<int> UnidadPesoBrutoValue { get; set; }
        public Nullable<bool> UnidadPesoBrutoValueSpecified { get; set; }
        public Nullable<int> UnidadPesoBruto { get; set; }
        public Nullable<int> UnidadPesoNetoValue { get; set; }
        public Nullable<bool> UnidadPesoNetoValueSpecified { get; set; }
        public Nullable<int> UnidadPesoNeto { get; set; }
        public Nullable<decimal> CantidadBultoValue { get; set; }
        public Nullable<bool> CantidadBultoValueSpecified { get; set; }
        public Nullable<decimal> CantidadBulto { get; set; }
        public Nullable<int> UnidadBultoValue { get; set; }
        public Nullable<bool> UnidadBultoValueSpecified { get; set; }
        public Nullable<int> UnidadBulto { get; set; }
        public Nullable<decimal> VolumenBultoValue { get; set; }
        public Nullable<bool> VolumenBultoValueSpecified { get; set; }
        public Nullable<decimal> VolumenBulto { get; set; }
        public Nullable<int> UnidadVolumenValue { get; set; }
        public Nullable<bool> UnidadVolumenValueSpecified { get; set; }
        public Nullable<int> UnidadVolumen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EcfEncabezado> EcfEncabezadoes { get; set; }
    }
}
