//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF.Recepcion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfEncabezadoEmisor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EcfEncabezadoEmisor()
        {
            this.EcfEncabezadoes = new HashSet<EcfEncabezado>();
        }
    
        public int Id { get; set; }
        public string RNCEmisor { get; set; }
        public string RazonSocialEmisor { get; set; }
        public string NombreComercial { get; set; }
        public string Sucursal { get; set; }
        public string DireccionEmisor { get; set; }
        public int MunicipioValue { get; set; }
        public bool MunicipioValueSpecified { get; set; }
        public Nullable<int> Municipio { get; set; }
        public int ProvinciaValue { get; set; }
        public bool ProvinciaValueSpecified { get; set; }
        public Nullable<int> Provincia { get; set; }
        public string CorreoEmisor { get; set; }
        public string WebSite { get; set; }
        public string ActividadEconomica { get; set; }
        public string CodigoVendedor { get; set; }
        public string NumeroFacturaInterna { get; set; }
        public decimal NumeroPedidoInternoValue { get; set; }
        public bool NumeroPedidoInternoValueSpecified { get; set; }
        public Nullable<decimal> NumeroPedidoInterno { get; set; }
        public string ZonaVenta { get; set; }
        public string RutaVenta { get; set; }
        public string InformacionAdicionalEmisor { get; set; }
        public string FechaEmision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EcfEncabezado> EcfEncabezadoes { get; set; }
        public virtual AprobacionComercial AprobacionComercial { get; set; }
    }
}
