//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF.Recepcion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfEncabezadoOtraMonedaImpuestosAdicionalesOtraMonedaImpuestoAdicionalOtraMoneda
    {
        public int Id { get; set; }
        public int TipoImpuestoOtraMoneda { get; set; }
        public decimal TasaImpuestoAdicionalOtraMoneda { get; set; }
        public decimal MontoImpuestoSelectivoConsumoEspecificoOtraMonedaValue { get; set; }
        public bool MontoImpuestoSelectivoConsumoEspecificoOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoImpuestoSelectivoConsumoEspecificoOtraMoneda { get; set; }
        public decimal MontoImpuestoSelectivoConsumoAdvaloremOtraMonedaValue { get; set; }
        public bool MontoImpuestoSelectivoConsumoAdvaloremOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> MontoImpuestoSelectivoConsumoAdvaloremOtraMoneda { get; set; }
        public decimal OtrosImpuestosAdicionalesOtraMonedaValue { get; set; }
        public bool OtrosImpuestosAdicionalesOtraMonedaValueSpecified { get; set; }
        public Nullable<decimal> OtrosImpuestosAdicionalesOtraMoneda { get; set; }
        public Nullable<int> ECFEncabezadoOtraMonedaId { get; set; }
        public Nullable<int> ECFEncabezadoOtraMonedaImpuestosAdicionalesOtraMonedaId { get; set; }
    
        public virtual EcfEncabezadoOtraMonedasImpuestosAdicionale EcfEncabezadoOtraMonedasImpuestosAdicionale { get; set; }
        public virtual EncabezadoOtraMoneda EncabezadoOtraMoneda { get; set; }
    }
}
