//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF.Recepcion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcfEncabezadoTotale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EcfEncabezadoTotale()
        {
            this.EcfEncabezadoes = new HashSet<EcfEncabezado>();
            this.ECFEncabezadoTotalesImpuestosAdicionalesImpuestoAdicionals = new HashSet<ECFEncabezadoTotalesImpuestosAdicionalesImpuestoAdicional>();
            this.AprobacionComercials = new HashSet<AprobacionComercial>();
        }
    
        public int Id { get; set; }
        public decimal MontoGravadoTotalValue { get; set; }
        public bool MontoGravadoTotalValueSpecified { get; set; }
        public Nullable<decimal> MontoGravadoTotal { get; set; }
        public decimal MontoGravadoI1Value { get; set; }
        public bool MontoGravadoI1ValueSpecified { get; set; }
        public Nullable<decimal> MontoGravadoI1 { get; set; }
        public decimal MontoGravadoI2Value { get; set; }
        public bool MontoGravadoI2ValueSpecified { get; set; }
        public Nullable<decimal> MontoGravadoI2 { get; set; }
        public decimal MontoGravadoI3Value { get; set; }
        public bool MontoGravadoI3ValueSpecified { get; set; }
        public Nullable<decimal> MontoGravadoI3 { get; set; }
        public decimal MontoExentoValue { get; set; }
        public bool MontoExentoValueSpecified { get; set; }
        public Nullable<decimal> MontoExento { get; set; }
        public short ITBIS1Value { get; set; }
        public bool ITBIS1ValueSpecified { get; set; }
        public Nullable<short> ITBIS1 { get; set; }
        public short ITBIS2Value { get; set; }
        public bool ITBIS2ValueSpecified { get; set; }
        public Nullable<short> ITBIS2 { get; set; }
        public short ITBIS3Value { get; set; }
        public bool ITBIS3ValueSpecified { get; set; }
        public Nullable<short> ITBIS3 { get; set; }
        public decimal TotalITBISValue { get; set; }
        public bool TotalITBISValueSpecified { get; set; }
        public Nullable<decimal> TotalITBIS { get; set; }
        public decimal TotalITBIS1Value { get; set; }
        public bool TotalITBIS1ValueSpecified { get; set; }
        public Nullable<decimal> TotalITBIS1 { get; set; }
        public decimal TotalITBIS2Value { get; set; }
        public bool TotalITBIS2ValueSpecified { get; set; }
        public Nullable<decimal> TotalITBIS2 { get; set; }
        public decimal TotalITBIS3Value { get; set; }
        public bool TotalITBIS3ValueSpecified { get; set; }
        public Nullable<decimal> TotalITBIS3 { get; set; }
        public decimal MontoImpuestoAdicionalValue { get; set; }
        public bool MontoImpuestoAdicionalValueSpecified { get; set; }
        public Nullable<decimal> MontoImpuestoAdicional { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal MontoNoFacturableValue { get; set; }
        public bool MontoNoFacturableValueSpecified { get; set; }
        public Nullable<decimal> MontoNoFacturable { get; set; }
        public decimal MontoPeriodoValue { get; set; }
        public bool MontoPeriodoValueSpecified { get; set; }
        public Nullable<decimal> MontoPeriodo { get; set; }
        public decimal SaldoAnteriorValue { get; set; }
        public bool SaldoAnteriorValueSpecified { get; set; }
        public Nullable<decimal> SaldoAnterior { get; set; }
        public decimal MontoAvancePagoValue { get; set; }
        public bool MontoAvancePagoValueSpecified { get; set; }
        public Nullable<decimal> MontoAvancePago { get; set; }
        public decimal ValorPagarValue { get; set; }
        public bool ValorPagarValueSpecified { get; set; }
        public Nullable<decimal> ValorPagar { get; set; }
        public decimal TotalITBISRetenidoValue { get; set; }
        public bool TotalITBISRetenidoValueSpecified { get; set; }
        public Nullable<decimal> TotalITBISRetenido { get; set; }
        public decimal TotalISRRetencionValue { get; set; }
        public bool TotalISRRetencionValueSpecified { get; set; }
        public Nullable<decimal> TotalISRRetencion { get; set; }
        public decimal TotalITBISPercepcionValue { get; set; }
        public bool TotalITBISPercepcionValueSpecified { get; set; }
        public Nullable<decimal> TotalITBISPercepcion { get; set; }
        public decimal TotalISRPercepcionValue { get; set; }
        public bool TotalISRPercepcionValueSpecified { get; set; }
        public Nullable<decimal> TotalISRPercepcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EcfEncabezado> EcfEncabezadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECFEncabezadoTotalesImpuestosAdicionalesImpuestoAdicional> ECFEncabezadoTotalesImpuestosAdicionalesImpuestoAdicionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobacionComercial> AprobacionComercials { get; set; }
    }
}
