//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF.Recepcion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoEnvio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoEnvio()
        {
            this.AprobacionComercials = new HashSet<AprobacionComercial>();
        }
    
        public int Id { get; set; }
        public string trackId { get; set; }
        public string codigo { get; set; }
        public string estado { get; set; }
        public string rnc { get; set; }
        public string fechaRecepcion { get; set; }
        public int IdMensajeEnvios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobacionComercial> AprobacionComercials { get; set; }
    }
}
