//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iECF.Recepcion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma_comp_elec
    {
        public string TipoeCF { get; set; }
        public string ENCF { get; set; }
        public string FechaVencimientoSecuencia { get; set; }
        public string TipoIngresos { get; set; }
        public string RNCEmisor { get; set; }
        public string RazonSocialEmisor { get; set; }
        public string RNCComprador { get; set; }
        public string RazonSocialComprador { get; set; }
        public Nullable<short> NumeroLinea { get; set; }
        public string NombreItem { get; set; }
        public Nullable<decimal> MontoItem { get; set; }
        public Nullable<decimal> MontoGravadoTotal { get; set; }
        public decimal MontoTotal { get; set; }
    }
}
